const universitiesData = {
  /* ── SRI LANKAN STATE UNIVERSITIES ── */
  uoc: {
    name: "University of Colombo",
    short: "UOC",
    location: "Colombo, Sri Lanka",
    country: "Sri Lanka",
    type: "local",
    tag: "State University",
    founded: 1921,
    ranking: "#1 in Sri Lanka",
    students: "~16,000",
    image: "/assets/uoc.jpg",
    logo: "/assets/uoc_logo.png",
    image2: "/assets/uoc_2.jpg",
    link: "https://cmb.ac.lk/",
    summary: "Located in the heart of the capital, the University of Colombo is consistently ranked as the #1 university in Sri Lanka. It is highly competitive and known for producing top-tier professionals in medicine, law, and the corporate sector. Its Faculty of Law is the oldest and most prestigious in the country.",
    bestKnownFor: "Medicine, Law, Management, and Computer Science.",
    keyDegrees: ["Medicine (MBBS)", "Law (LLB)", "Computer Science", "Management"],
    degrees: [
      { category: "Medicine & Health Sciences", details: "MBBS, BSc in Nursing, BSc in Physiotherapy, BSc in Medical Laboratory Science" },
      { category: "Computing & Technology", details: "BSc in Computer Science, BSc in Software Engineering, BSc in Data Science" },
      { category: "Management & Business", details: "BBA, BSc in Management & Information Systems, BSc in Accounting" },
      { category: "Law", details: "LLB (Bachelor of Laws) — oldest and most competitive law program in Sri Lanka" },
      { category: "Arts & Humanities", details: "BA in Sinhala, English, History, Geography, Economics, Political Science, Philosophy, Pali & Buddhist Studies" }
    ]
  },
  uom: {
    name: "University of Moratuwa",
    short: "UOM",
    location: "Moratuwa, Sri Lanka",
    country: "Sri Lanka",
    type: "local",
    tag: "State University",
    founded: 1972,
    ranking: "Top Engineering University in Sri Lanka",
    students: "~10,000",
    image: "/assets/uom.jpg",
    logo: "/assets/uom_logo.png",
    image2: "/assets/uom_2.jpg",
    link: "https://uom.lk/",
    summary: "The University of Moratuwa is the undisputed powerhouse of technology and engineering in Sri Lanka. If you dream of becoming a software engineer, data scientist, or technical architect, this is the most sought-after destination. Its graduates are recruited heavily by global tech companies.",
    bestKnownFor: "Software Engineering, Computer Science, Civil & Electronic Engineering, and Architecture.",
    keyDegrees: ["BSc Engineering", "BSc IT", "B.Architecture", "AI & Data Science"],
    degrees: [
      { category: "Engineering Disciplines", details: "BSc Eng in Software, Electronic & Telecom, Mechanical, Civil, Chemical, Earth Resources, and Material Engineering" },
      { category: "Information Technology", details: "BSc in IT, BSc in IT & Management, BSc in Artificial Intelligence" },
      { category: "Architecture & Design", details: "Bachelor of Architecture (BArch), Bachelor of Design in Fashion Design & Product Design" },
      { category: "Quantity Surveying", details: "BSc in Quantity Surveying — one of the best in Asia" }
    ]
  },
  uop: {
    name: "University of Peradeniya",
    short: "UOP",
    location: "Kandy, Sri Lanka",
    country: "Sri Lanka",
    type: "local",
    tag: "State University",
    founded: 1942,
    ranking: "Largest University in Sri Lanka",
    students: "~17,000",
    image: "/assets/uop.jpg",
    logo: "/assets/uop_logo.png",
    image2: "/assets/uop_2.jpg",
    link: "https://www.pdn.ac.lk/",
    summary: "Set on a breathtaking riverside campus in Kandy, the University of Peradeniya is the largest university in Sri Lanka. It is a comprehensive research university, excelling in medical sciences, agricultural research, and engineering. The campus is considered one of the most beautiful in Asia.",
    bestKnownFor: "Medicine, Veterinary Science, Agriculture, Engineering, and Allied Health Sciences.",
    keyDegrees: ["MBBS", "BDS (Dental)", "BVSc", "BSc Engineering", "BSc Agriculture"],
    degrees: [
      { category: "Medical & Dental Sciences", details: "MBBS (Medicine), BDS (Bachelor of Dental Surgery), BSc in Physiotherapy, BSc in Nursing" },
      { category: "Veterinary Science", details: "BVSc — One of only two veterinary faculties in Sri Lanka" },
      { category: "Engineering & Technology", details: "BSc Eng in Computer, Electrical, Civil, Mechanical, and Chemical Engineering" },
      { category: "Agriculture", details: "BSc Agriculture, BSc Food Science & Technology, BSc Agri-Business Management" },
      { category: "Sciences & Arts", details: "BSc in Chemistry, Physics, Mathematics, Molecular Biology, and BA in Humanities subjects" }
    ]
  },
  usj: {
    name: "University of Sri Jayewardenepura",
    short: "USJ",
    location: "Nugegoda, Sri Lanka",
    country: "Sri Lanka",
    type: "local",
    tag: "State University",
    founded: 1958,
    ranking: "#2 for Management in Sri Lanka",
    students: "~15,000",
    image: "/assets/usj.jpg",
    logo: "/assets/usj_logo.png",
    image2: "/assets/usj.jpg",
    link: "https://www.sjp.ac.lk/",
    summary: "Affectionately called 'Japura,' this university hosts the largest Management faculty in the country. If you want to enter the Sri Lankan corporate world — banking, finance, or marketing — Japura is the most respected choice. Its Faculty of Applied Sciences is also growing rapidly in tech-related fields.",
    bestKnownFor: "Management, Business Administration, Applied Sciences, and Medicine.",
    keyDegrees: ["BCom / BBA", "BSc Cyber Security", "MBBS", "BSc Finance"],
    degrees: [
      { category: "Management & Commerce", details: "BSc in Accounting, Business Administration, Finance, Marketing, Human Resource Management" },
      { category: "Applied Sciences & Tech", details: "BSc in Cyber Security, Computing & Information Systems, Food Science, Environmental Science" },
      { category: "Medical Sciences", details: "MBBS, BSc in Medical Laboratory Science, BSc in Pharmacy" },
      { category: "Graduate Studies", details: "Postgraduate degrees in Business, Science, and Social Sciences" }
    ]
  },
  uok: {
    name: "University of Kelaniya",
    short: "UOK",
    location: "Kelaniya, Sri Lanka",
    country: "Sri Lanka",
    type: "local",
    tag: "State University",
    founded: 1959,
    ranking: "Top 5 in Sri Lanka",
    students: "~19,000",
    image: "/assets/uok.jpg",
    logo: "/assets/uok_logo.png",
    image2: "/assets/uok.jpg",
    link: "https://www.kln.ac.lk/",
    summary: "The University of Kelaniya is highly ranked for its humanities, modern languages, and social sciences. It has a very strong Commerce faculty and a growing IT footprint. The Medical faculty, based in Ragama, is among the country's finest, known particularly for excellence in speech sciences and dentistry.",
    bestKnownFor: "Commerce, Information Technology, Languages, Mass Communication, and Medicine.",
    keyDegrees: ["BCom", "BSc MIT", "MBBS", "BA Mass Comm"],
    degrees: [
      { category: "Commerce & Management", details: "BCom (Special), BSc in Finance, BSc in Management & Information Technology" },
      { category: "Computing & Tech", details: "BSc in Software Engineering, BSc in Networking" },
      { category: "Medicine", details: "MBBS, BDS, BSc in Speech & Hearing Sciences" },
      { category: "Humanities & Social Sciences", details: "BA in Mass Communication, English, International Studies, Modern Languages, Sinhala, History" }
    ]
  },
  ujf: {
    name: "University of Jaffna",
    short: "UOJ",
    location: "Jaffna, Sri Lanka",
    country: "Sri Lanka",
    type: "local",
    tag: "State University",
    founded: 1974,
    ranking: "Top 8 in Sri Lanka",
    students: "~12,000",
    image: "/assets/ujf.jpg",
    logo: "/assets/ujf_logo.png",
    image2: null,
    link: "https://www.jfn.ac.lk/",
    summary: "The University of Jaffna is the premier institution of the Northern Province and an important center for higher education in Sri Lanka. It offers faculties in medicine, agriculture, engineering, arts, and management, making it a comprehensive university serving the Northern and Eastern communities.",
    bestKnownFor: "Medicine, Agriculture, Engineering, and Humanities.",
    keyDegrees: ["MBBS", "BSc Agriculture", "BSc Engineering", "BBA"],
    degrees: [
      { category: "Medicine", details: "MBBS — Faculty of Medicine is one of the most respected in Northern Sri Lanka" },
      { category: "Engineering", details: "BSc Engineering in Civil, Electrical, and Computer Engineering" },
      { category: "Agriculture", details: "BSc Agriculture, BSc Food Science & Technology" },
      { category: "Arts & Management", details: "BA in multiple disciplines, BBA, BCom" }
    ]
  },
  uor: {
    name: "University of Ruhuna",
    short: "UOR",
    location: "Matara, Sri Lanka",
    country: "Sri Lanka",
    type: "local",
    tag: "State University",
    founded: 1978,
    ranking: "Top 8 in Sri Lanka",
    students: "~10,000",
    image: "/assets/uor.jpg",
    logo: "/assets/uor_logo.png",
    image2: null,
    link: "https://www.ruh.ac.lk/",
    summary: "The University of Ruhuna, situated in the beautiful Southern Province, is a well-rounded state university with particular strengths in engineering, fisheries, agriculture, and medicine. It serves as the main higher education institution for southern Sri Lanka and is growing in its research output.",
    bestKnownFor: "Engineering, Fisheries, Agriculture, and Humanities.",
    keyDegrees: ["BSc Engineering", "BSc Fisheries", "MBBS", "BSc Agriculture"],
    degrees: [
      { category: "Engineering", details: "BSc Eng in Civil, Electrical, Mechanical, and Computing" },
      { category: "Medicine & Health", details: "MBBS, BSc in Health Promotion Sciences" },
      { category: "Fisheries & Marine", details: "BSc in Fisheries & Marine Sciences — one of Sri Lanka's only programs" },
      { category: "Agriculture", details: "BSc Agriculture, BSc Food Science" },
      { category: "Humanities & Social Sciences", details: "BA programs in Sinhala, History, Economics, and Sociology" }
    ]
  },
  sau: {
    name: "Sabaragamuwa University of Sri Lanka",
    short: "SUSL",
    location: "Belihuloya, Sri Lanka",
    country: "Sri Lanka",
    type: "local",
    tag: "State University",
    founded: 1991,
    ranking: "Top 10 in Sri Lanka",
    students: "~8,000",
    image: "/assets/sau.jpg",
    logo: "/assets/sau_logo.png",
    image2: null,
    link: "https://www.sab.ac.lk/",
    summary: "Located in the scenic Belihuloya area, Sabaragamuwa University is known for its natural sciences, tourism, and social sciences faculties. Its Tourism & Hospitality Management program is considered among the best in Sri Lanka, attracting students from across the country.",
    bestKnownFor: "Tourism, Social Sciences, Natural Sciences, and Management.",
    keyDegrees: ["BSc Tourism", "BSc Natural Sciences", "BBA", "BSc IT"],
    degrees: [
      { category: "Tourism & Hospitality", details: "BSc in Tourism & Hospitality Management — top-ranked program in Sri Lanka" },
      { category: "Natural Sciences", details: "BSc in Geomatics, BSc in Natural Resources, BSc in Applied Sciences" },
      { category: "Management", details: "BBA, BSc in Management Information Systems" },
      { category: "Social Sciences", details: "BA in Communication & Media, BSc in Community Development" }
    ]
  },
  waya: {
    name: "Wayamba University of Sri Lanka",
    short: "WUSL",
    location: "Kuliyapitiya, Sri Lanka",
    country: "Sri Lanka",
    type: "local",
    tag: "State University",
    founded: 1999,
    ranking: "Top 12 in Sri Lanka",
    students: "~6,000",
    image: "/assets/waya.jpg",
    logo: "/assets/waya_logo.png",
    image2: null,
    link: "https://www.wyb.ac.lk/",
    summary: "Wayamba University, in the North Western Province, focuses on business management, agriculture and plantation, and applied sciences. It has a growing reputation for its agri-business programs that prepare graduates for Sri Lanka's plantation and export agriculture sectors.",
    bestKnownFor: "Agri-Business, Plantation Management, and Business.",
    keyDegrees: ["BSc Agri-Business", "BBA", "BSc Technology", "BSc Bio-Systems"],
    degrees: [
      { category: "Agriculture & Plantation", details: "BSc in Agri-Business Management, BSc in Plantation Management" },
      { category: "Business", details: "BBA, BCom, BSc in Accounting" },
      { category: "Applied Sciences", details: "BSc in Technology, BSc in Bio-Systems Technology" }
    ]
  },
  raju: {
    name: "Rajarata University of Sri Lanka",
    short: "RUSL",
    location: "Mihintale, Sri Lanka",
    country: "Sri Lanka",
    type: "local",
    tag: "State University",
    founded: 1996,
    ranking: "Top 12 in Sri Lanka",
    students: "~7,000",
    image: "/assets/raju.jpg",
    logo: "/assets/raju_logo.png",
    image2: null,
    link: "https://www.rjt.ac.lk/",
    summary: "Rajarata University, close to Anuradhapura in the North Central Province, offers programs in agriculture, social sciences, management, and applied sciences. It is an important institution for the northern agricultural heartland of Sri Lanka and holds special significance for students from the Anuradhapura district.",
    bestKnownFor: "Agriculture, Social Sciences, and Management.",
    keyDegrees: ["BSc Agriculture", "BA Social Sciences", "BBA", "BSc Applied Sciences"],
    degrees: [
      { category: "Agriculture", details: "BSc Agriculture, BSc Agricultural Technology & Management" },
      { category: "Social Sciences & Humanities", details: "BA in Archaeology, Sociology, Information Technology, and Public Administration" },
      { category: "Management", details: "BBA, BSc in Management" },
      { category: "Applied Sciences", details: "BSc in Applied Sciences" }
    ]
  },
  uvpa: {
    name: "University of the Visual & Performing Arts",
    short: "UVPA",
    location: "Colombo, Sri Lanka",
    country: "Sri Lanka",
    type: "local",
    tag: "State University",
    founded: 2002,
    ranking: "Only Arts Focused State University",
    students: "~2,500",
    image: null,
    logo: null,
    image2: null,
    link: "https://www.vpa.ac.lk/",
    summary: "Sri Lanka's only state university dedicated entirely to the visual and performing arts. It offers degrees in dance, drama, music, fine arts, and design. Students who are passionate about creative disciplines and want a professionally recognized degree in the arts will find UVPA as their ideal destination.",
    bestKnownFor: "Fine Arts, Dance, Drama, Music, and Design.",
    keyDegrees: ["BA Fine Arts", "BA Dance", "BA Drama", "BA Music"],
    degrees: [
      { category: "Fine Arts & Design", details: "BA in Fine Arts, Graphic Design, and Spatial Design" },
      { category: "Performing Arts", details: "BA in Dance, Drama, and Music (multiple instruments & vocal)" },
      { category: "Theatre & Film", details: "BA in Theatre and BA in Film Studies" }
    ]
  },

  /* ── FOREIGN UNIVERSITIES ── */
  mit: {
    name: "Massachusetts Institute of Technology",
    short: "MIT",
    location: "Cambridge, Massachusetts, USA",
    country: "USA",
    type: "foreign",
    tag: "World #1 Engineering",
    founded: 1861,
    ranking: "#1 QS World 2024",
    students: "~11,000",
    image: "/assets/mit.jpg",
    logo: "/assets/mit_logo.png",
    image2: "/assets/mit.jpg",
    link: "https://web.mit.edu/",
    summary: "Consistently ranked the #1 university in the world, MIT is the absolute pinnacle for science and technology. It is famous for its culture of innovation, hands-on research, and entrepreneurship. MIT alumni have founded companies worth trillions of dollars and have won 97+ Nobel Prizes.",
    bestKnownFor: "Artificial Intelligence, Robotics, Quantum Computing, Aerospace Engineering, and Physics.",
    keyDegrees: ["Computer Science", "Aerospace Eng", "Physics", "AI & Robotics"],
    degrees: [
      { category: "Computer Science & Engineering", details: "BSc in EECS (Electrical Engineering & Computer Science), Course 6: the most competitive program at MIT" },
      { category: "Engineering", details: "BSc in Mechanical Engineering, Civil & Environmental Engineering, Aerospace Engineering, Nuclear Engineering" },
      { category: "Science", details: "BSc in Physics, Chemistry, Mathematics, Biology, and Brain & Cognitive Sciences" },
      { category: "Architecture & Planning", details: "Bachelor of Science in Architecture — one of the top programs globally" },
      { category: "Economics & Management", details: "BSc in Economics, Management Science" }
    ]
  },
  stanford: {
    name: "Stanford University",
    short: "Stanford",
    location: "Silicon Valley, California, USA",
    country: "USA",
    type: "foreign",
    tag: "Silicon Valley's University",
    founded: 1885,
    ranking: "#3 QS World 2024",
    students: "~17,000",
    image: "/assets/stanford.jpg",
    logo: "/assets/stanford_logo.png",
    image2: "/assets/stanford_2.jpg",
    link: "https://www.stanford.edu/",
    summary: "Located in the heart of Silicon Valley, Stanford is the university that shaped the modern tech world. Google, Netflix, Instagram, Yahoo, and hundreds of other companies were founded by Stanford alumni. It has an unmatched entrepreneurial culture and is particularly dominant in Computer Science and Business.",
    bestKnownFor: "Computer Science, Artificial Intelligence, and Entrepreneurship.",
    keyDegrees: ["CS & AI", "Data Science", "Economics", "International Relations"],
    degrees: [
      { category: "Computer Science & AI", details: "BSc in Computer Science with tracks in AI, HCI, Graphics, Systems, and Theory — the most sought-after CS degree in the world" },
      { category: "Engineering", details: "BSc in Electrical Engineering, Biomedical Engineering, Civil Engineering" },
      { category: "Liberal Arts", details: "BA in Economics, International Relations, Political Science, and Psychology" },
      { category: "Earth & Energy", details: "BSc in Earth Systems, Energy Resources Engineering" }
    ]
  },
  harvard: {
    name: "Harvard University",
    short: "Harvard",
    location: "Cambridge, Massachusetts, USA",
    country: "USA",
    type: "foreign",
    tag: "World's Most Prestigious",
    founded: 1636,
    ranking: "#4 QS World 2024",
    students: "~23,000",
    image: "/assets/harvard.jpg",
    logo: "/assets/harvard_logo.png",
    image2: "/assets/harvard_2.jpg",
    link: "https://www.harvard.edu/",
    summary: "As America's oldest university, Harvard is the global symbol of academic prestige. It has produced 8 US Presidents, over 160 Nobel Laureates, and countless world leaders. Harvard is particularly dominant in Law, Medicine, Business, and Political Science, and has the largest academic library in the world.",
    bestKnownFor: "Law, Medicine, Business, Political Science, and Economics.",
    keyDegrees: ["Pre-Law", "Pre-Med", "Economics", "Government"],
    degrees: [
      { category: "Pre-Medical Sciences", details: "BA/BSc in Molecular & Cellular Biology, Biomedical Engineering, Chemistry, and Neuroscience" },
      { category: "Law & Government", details: "BA in Government, Political Science, and Social Studies (LLB is a postgraduate degree at Harvard)" },
      { category: "Economics & Business", details: "BA in Economics and Applied Mathematics — the gateway to Harvard Business School" },
      { category: "Humanities", details: "BA in English, History, Philosophy, and Comparative Literature" }
    ]
  },
  oxford: {
    name: "University of Oxford",
    short: "Oxford",
    location: "Oxford, United Kingdom",
    country: "UK",
    type: "foreign",
    tag: "World's Oldest English University",
    founded: 1096,
    ranking: "#3 QS World 2024",
    students: "~26,000",
    image: "/assets/oxford.jpg",
    logo: "/assets/oxford_logo.png",
    image2: "/assets/oxford_2.jpg",
    link: "https://www.ox.ac.uk/",
    summary: "The oldest university in the English-speaking world, Oxford uses a unique tutorial system where students study in tiny groups of 1-3 with world-class professors. Oxford alumni have included 28 British Prime Ministers, 28 Nobel Laureates, and some of the world's most influential thinkers. It is especially strong in both classical scholarship and modern science.",
    bestKnownFor: "Medicine, Law, Philosophy, Mathematics, and English Literature.",
    keyDegrees: ["BA PPE", "Medicine (MBChB)", "Law", "Computer Science"],
    degrees: [
      { category: "Medicine & Health", details: "BA Medical Sciences (pre-clinical) leading to BM BCh — one of the most competitive degrees in the world" },
      { category: "Mathematics & Computing", details: "BA in Mathematics, BA in Computer Science, BA in Mathematics & Computer Science joint degree" },
      { category: "Humanities", details: "BA in PPE (Philosophy, Politics & Economics) — the degree of Oxford prime ministers; BA in English, History, Law" },
      { category: "Sciences", details: "BA/BSc in Biochemistry, Biology, Chemistry, Physics, and Earth Sciences" }
    ]
  },
  imperial: {
    name: "Imperial College London",
    short: "Imperial",
    location: "London, United Kingdom",
    country: "UK",
    type: "foreign",
    tag: "UK's Top Tech University",
    founded: 1907,
    ranking: "#6 QS World 2024",
    students: "~19,000",
    image: "/assets/imperial.jpg",
    logo: "/assets/imperial_logo.png",
    image2: "/assets/imperial_2.jpg",
    link: "https://www.imperial.ac.uk/",
    summary: "Often described as the UK's equivalent of MIT, Imperial College London focuses exclusively on science, engineering, medicine, and business. It is right in central London and has produced some of the world's most influential scientists and engineers. Its graduates are among the highest earners in the UK.",
    bestKnownFor: "Engineering, Computing, Biosciences, and Medicine.",
    keyDegrees: ["MEng Computing", "BEng Electrical", "Biosciences", "BSc Physics"],
    degrees: [
      { category: "Computing & Engineering", details: "MEng Computing (a 4-year integrated master's), BEng in Electronic & Electrical Engineering, Mechanical Engineering, Civil Engineering" },
      { category: "Natural Sciences", details: "BSc in Physics, Chemistry, Mathematics, Biochemistry, and Biotechnology" },
      { category: "Medicine", details: "MBBS/BSc — six-year integrated medical program" },
      { category: "Business", details: "BSc in Management — the Imperial College Business School is highly ranked for quantitative finance and entrepreneurship" }
    ]
  },
  nus: {
    name: "National University of Singapore",
    short: "NUS",
    location: "Singapore",
    country: "Singapore",
    type: "foreign",
    tag: "#1 in Asia",
    founded: 1905,
    ranking: "#8 QS World 2024",
    students: "~40,000",
    image: "/assets/nus.jpg",
    logo: "/assets/nus_logo.png",
    image2: "/assets/nus_2.jpg",
    link: "https://nus.edu.sg/",
    summary: "The National University of Singapore is the top-ranked university in Asia and one of the best globally. It is an excellent option for Sri Lankan students given its relative proximity, multicultural environment, and generous scholarship opportunities. Singapore's tech and finance ecosystem makes NUS graduates extremely valuable in the job market.",
    bestKnownFor: "Computer Science, Law, Medicine, Business, and Engineering.",
    keyDegrees: ["BSc Computer Science", "BEng Computer", "Business Admin", "Law"],
    degrees: [
      { category: "Computing & Technology", details: "BSc in Computer Science, BSc in Information Security, BSc in Business Analytics" },
      { category: "Engineering", details: "BEng in Computer Engineering, Chemical Engineering, Civil Engineering, Electrical Engineering" },
      { category: "Business", details: "BBA (Business Administration) — highly ranked globally; BSc in Accountancy" },
      { category: "Medicine & Dentistry", details: "MBBS, BDS — highly competitive, world-class facilities" },
      { category: "Law", details: "LLB — the #1 law school in Asia" }
    ]
  },
  edinburgh: {
    name: "University of Edinburgh",
    short: "Edinburgh",
    location: "Edinburgh, Scotland, UK",
    country: "UK",
    type: "foreign",
    tag: "Scotland's Top University",
    founded: 1583,
    ranking: "#22 QS World 2024",
    students: "~39,000",
    image: "/assets/edinburgh.jpg",
    logo: "/assets/edinburgh_logo.png",
    image2: null,
    link: "https://www.ed.ac.uk/",
    summary: "One of the ancient universities of Scotland and among the oldest in the world, the University of Edinburgh has produced an extraordinary list of alumni including Charles Darwin, David Hume, and James Clerk Maxwell. It is a research powerhouse particularly strong in medicine, AI, and informatics.",
    bestKnownFor: "Medicine, Informatics, Law, and Social Sciences.",
    keyDegrees: ["MBBS / MBChB", "BSc AI", "BSc Computer Science", "Law"],
    degrees: [
      { category: "Medicine & Veterinary", details: "MBChB (6-year Medicine), BSc in Nursing, BVSc (Veterinary Science)" },
      { category: "Informatics & Computing", details: "BSc in Computer Science, BSc in Artificial Intelligence, BSc in Data Science" },
      { category: "Law & Social Sciences", details: "LLB, MA in Politics, MA in Economics, MA in International Relations" },
      { category: "Humanities & Arts", details: "MA in English Literature, History, Philosophy, and Linguistics" }
    ]
  },
  toronto: {
    name: "University of Toronto",
    short: "U of T",
    location: "Toronto, Ontario, Canada",
    country: "Canada",
    type: "foreign",
    tag: "#1 in Canada",
    founded: 1827,
    ranking: "#21 QS World 2024",
    students: "~97,000",
    image: "/assets/toronto.jpg",
    logo: "/assets/toronto_logo.png",
    image2: null,
    link: "https://www.utoronto.ca/",
    summary: "Canada's top-ranked university and one of the world's great research institutions, U of T is located in one of the most multicultural cities on Earth. It is particularly known for its AI research (the university where deep learning was pioneered), medicine, and law. Canada's welcoming immigration pathways make U of T an attractive destination for international students.",
    bestKnownFor: "AI & Machine Learning, Medicine, Computer Science, and Engineering.",
    keyDegrees: ["BSc Computer Science", "BEng", "Medicine", "BSc Life Sciences"],
    degrees: [
      { category: "Computer Science & AI", details: "BSc in Computer Science — the birthplace of modern deep learning research, with researchers like Geoffrey Hinton" },
      { category: "Engineering", details: "BEng in Electrical, Mechanical, Computer, Chemical, and Industrial Engineering" },
      { category: "Medicine & Health", details: "MD (Doctor of Medicine) — one of Canada's top medical programs" },
      { category: "Commerce & Economics", details: "BCom at Rotman School of Management, BA in Economics" },
      { category: "Arts & Science", details: "BA in Political Science, Psychology, International Relations" }
    ]
  },
  melbourne: {
    name: "University of Melbourne",
    short: "UniMelb",
    location: "Melbourne, Victoria, Australia",
    country: "Australia",
    type: "foreign",
    tag: "#1 in Australia",
    founded: 1853,
    ranking: "#14 QS World 2024",
    students: "~56,000",
    image: "/assets/melbourne.jpg",
    logo: "/assets/melbourne_logo.png",
    image2: null,
    link: "https://www.unimelb.edu.au/",
    summary: "Australia's top-ranked university, the University of Melbourne sits in one of the world's most livable cities and has a global reputation for research. It is part of the Group of Eight elite Australian universities and is particularly strong in law, medicine, and arts. Australia's post-study work visa options make Melbourne especially attractive for international students.",
    bestKnownFor: "Law, Medicine, Arts, Engineering, and Business.",
    keyDegrees: ["LLB / JD", "MBBS", "BSc Engineering", "BCom"],
    degrees: [
      { category: "Law", details: "LLB/JD — Australia's top law program, highly respected internationally" },
      { category: "Medicine & Health", details: "MD (Doctor of Medicine), Bachelor of Biomedicine, BSc in Nursing" },
      { category: "Engineering & IT", details: "BSc in Computer Science, BE in Software, Electrical, Civil, and Mechanical Engineering" },
      { category: "Commerce & Economics", details: "BCom — among the best in Australia; BA in Economics" },
      { category: "Arts & Humanities", details: "BA in a wide range of subjects including Cultural Studies, Creative Arts, and Political Science" }
    ]
  },
  monash: {
    name: "Monash University",
    short: "Monash",
    location: "Melbourne, Victoria, Australia",
    country: "Australia",
    type: "foreign",
    tag: "Australia's Global University",
    founded: 1958,
    ranking: "#37 QS World 2024",
    students: "~86,000",
    image: "/assets/monash.jpg",
    logo: "/assets/monash_logo.png",
    image2: null,
    link: "https://www.monash.edu/",
    summary: "Monash is Australia's largest university and one of the country's elite research institutions. It has a large and welcoming international community, generous scholarships, and a campus in Kuala Lumpur that allows students to experience Australia-quality education at lower cost. Strong pathways to permanent residency in Australia make Monash a popular choice.",
    bestKnownFor: "Pharmacy, Engineering, Law, and Business.",
    keyDegrees: ["Pharmacy", "BSc Engineering", "LLB", "BCom / BBA"],
    degrees: [
      { category: "Pharmacy & Medicine", details: "Bachelor of Pharmacy — one of Australia's top pharmacy programs; Doctor of Medicine" },
      { category: "Engineering & IT", details: "BE in Software, Electrical, Civil, Aerospace, and Mechanical Engineering" },
      { category: "Law", details: "LLB — Monash Law School is among Australia's most prestigious" },
      { category: "Business & Economics", details: "BCom, BBA at Monash Business School" },
      { category: "Arts", details: "BA with multiple discipline tracks" }
    ]
  }
};
